export const frasesDesmotivacionais = {
  1: 'Você não é tão bom quanto pensa que é.',
  2: 'Veja como tudo acabou ontem e se decepcione mais um dia!⚡',
  3: 'Gratidão por todos os conselhos motivacionais que me fizeram desmotivar 😒',
  4: 'Agora e daqui pra frente, é só ladeira abaixo ⚡',
  5: 'Quando a vida parecer difícil lembre-se que tudo pode piorar 👎🏼',
  6: 'Não desanime, as piores coisas da vida ainda estão chegando por aí!⚡',
  7: 'Vencedores nunca param de se vangloriar por suas vitórias. Como sei? Eu vejo, nunca ganhei 😂',
  8: 'Não se preocupe, você não é o único que está desmotivado. Todos estão 😂',
  9: 'Aprendi da maneira mais difícil que nasci pra tentar, tentar, tentar e nunca conseguir 😫',
  10: 'Nunca tente piorar o que já está ruim. Deixe que a vida se encarrega de fazer isso pra você 😉',
  11: 'Nunca é tarde demais para errar mais uma vez 😆',
  12: 'Não se preocupe se você perder, nós não esperávamos mais de você! ⚡',
  13: 'Pare de reclamar de tudo e comece a aceitar que tudo deu errado pra você!👀',
  14: 'Procrastinar é sempre a melhor escolha para você se sentir um completo imbecil 😜',
  15: 'O caminho para o sucesso não está no seu mapa da vida. Aceite!👀',
  16: 'Tá difícil? A vida é realmente muito mais difícil para quem é um completo idiota.😂',
  17: 'Pare de tratar como lição mais uma das suas falhas 😒',
  18: 'Mais um dia que se inicia e novas oportunidades para errar surgem com esse novo amanhecer! 😂',
  19: 'Há sempre um espaço inútil para não ser aproveitado na vida de quem não tem o que fazer 😅',
  20: 'Pare e pense: todas as suas falhas tem o mesmo causador em comum: Você! 😂',
  21: 'Todo mundo tem um propósito na vida mas nem todo mundo vai encontrá-lo. Faz parte 😏',
  22: 'A vida é o que acontece quando você está ocupado lendo frases motivacionais',
  23: 'A vida é como um pote de sorvete, que quando você abre, só tem feijão 😂',
  24: 'Não descanse antes de reclamar de tudo.',
  25: 'Pode ser que o seu propósito na vida seja servir de aviso para os outros. 💡',
  26: 'A vida é uma série de coisas que preferiríamos não fazer. 😎',
  27: 'A estrada para o sucesso está sempre em construção. 🛣',
  28: 'Será fácil? Não. Vale a pena? Absolutamente não!',
  29: 'Quando as coisas ficam difíceis, as difíceis ficam ainda mais difíceis.',
  30: 'O primeiro passo para o fracasso é tentar',
  31: 'Aqueles que duvidam de sua capacidade provavelmente têm um motivo válido.',
};
