export const frasesDesmotivacionais = [
  'Você não é tão bom quanto pensa que é.',
  'Veja como tudo acabou ontem e se decepcione mais um dia!⚡',
  'Gratidão por todos os conselhos motivacionais que me fizeram desmotivar 😒',
  'Agora e daqui pra frente, é só ladeira abaixo ⚡',
  'Quando a vida parecer difícil lembre-se que tudo pode piorar 👎🏼',
  'Não desanime, as piores coisas da vida ainda estão chegando por aí!⚡',
  'Vencedores nunca param de se vangloriar por suas vitórias. Como sei? Eu vejo, nunca ganhei 😂',
  'Não se preocupe, você não é o único que está desmotivado. Todos estão 😂',
  'Aprendi da maneira mais difícil que nasci pra tentar, tentar, tentar e nunca conseguir 😫',
  'Nunca tente piorar o que já está ruim. Deixe que a vida se encarrega de fazer isso pra você 😉',
  'Nunca é tarde demais para errar mais uma vez 😆',
  'Não se preocupe se você perder, nós não esperávamos mais de você! ⚡',
  'Pare de reclamar de tudo e comece a aceitar que tudo deu errado pra você!👀',
  'Procrastinar é sempre a melhor escolha para você se sentir um completo imbecil 😜',
  'O caminho para o sucesso não está no seu mapa da vida. Aceite!👀',
  'Tá difícil? A vida é realmente muito mais difícil para quem é um completo idiota.😂',
  'Pare de tratar como lição mais uma das suas falhas 😒',
  'Mais um dia que se inicia e novas oportunidades para errar surgem com esse novo amanhecer! 😂',
  'Há sempre um espaço inútil para não ser aproveitado na vida de quem não tem o que fazer 😅',
  'Pare e pense: todas as suas falhas tem o mesmo causador em comum: Você! 😂',
  'Todo mundo tem um propósito na vida mas nem todo mundo vai encontrá-lo. Faz parte 😏',
  'A vida é o que acontece quando você está ocupado lendo frases motivacionais',
  'A vida é como um pote de sorvete, que quando você abre, só tem feijão 😂',
  'Não descanse antes de reclamar de tudo.',
  'Pode ser que o seu propósito na vida seja servir de aviso para os outros. 💡',
  'A vida é uma série de coisas que preferiríamos não fazer. 😎',
  'A estrada para o sucesso está sempre em construção. 🛣',
  'Será fácil? Não. Vale a pena? Absolutamente não!',
  'Quando as coisas ficam difíceis, as difíceis ficam ainda mais difíceis.',
  'O primeiro passo para o fracasso é tentar',
  'Aqueles que duvidam de sua capacidade provavelmente têm um motivo válido.',
];
